config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"

    post "/signup", to: "users#create"
    get "/signup", to: "users#new"

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"

    resources :users do
      member do
        get :following, :followers
      end
    end

    resources :users
    resources :account_activations, only: :edit
    resources :password_resets, only: %i(new create edit update)
    resources :microposts, only: %i(create destroy)
    resources :relationships, only: %i(create destroy)
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "error.error_valid"  %>
      <%= pluralize object.errors.count, t("error.error") %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts" >
    <%= render @feed_items %>
  </ol>
  <%== pagy_bootstrap_nav(@pagy) %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: t("error.compose_new_micropost") %>
  </div>
  <%= f.submit t("error.post"), class: "btn btn-primary" %>
  <span class="image">
    <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
  </span>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a>
    <%= link_to t("following"), following_user_path(@user) %>
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
  </a>
  <a>
    <%= link_to t("followers"), following_user_path(@user) %>
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: Settings.settings.length_user_info), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to t("error.user_info"), current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>